### ISSUE TITLE
PCA-ICA results with low dimensionality dataset

### ISSUE THREAD

**Issue by cgaletzka** [CRen2333/Wide-field-calcium-imaging#1]
Hi,

Thank you for making this code available!

I am doing widefield imaging and am trying to apply the PCA-ICA method for extracting region activity and artifacts. I registered all frames to the same template. I then calculated df/F pixel-wise and thresholded my FOV such that dF/F around all edges (outside of labeled region) is set to 0. I see synchronous activity in these dF/F traces in several areas with dF/F values up to 0.6. 

The dimensionality of my dataset is relatively low (first 6 PCA components explain 95% variance). However, when I plot these components, only 1 component can be clearly identified as a non-artifact. All other components appear blank (uniform color in the plot) or they concentrate on the edges.

I am not sure how to interpret these results or change my dataset. Could you please let me know if this is a common issue and if there are steps to address this? Is it correct that I included all of the pixels previously set to 0 in the PCA?

**Comment by west0883** [comment]
Hi, 

No, you do not include the pixels set to 0 in the PCA. Instead, you remove them completely. When you reshape your images into 2D, you would not include those pixels in the pixel dimension.

Ex: I have an image stack of 256 pixels x 256 pixels x 6000 frames that I would convert into a matrix of 65,536 pixels x 6000 frames before PCA. If I set 5,000 pixels outside the FOV to 0, would remove them and now have a matrix of 60,536 pixels x 6000 frames. 

You need to keep track of the indices of those pixels so you can reconstruct images later. 

Thanks,
Sarah

**Comment by CRen2333** [comment]
> Hi,
> 
> No, you do not include the pixels set to 0 in the PCA. Instead, you remove them completely. When you reshape your images into 2D, you would not include those pixels in the pixel dimension.
> 
> Ex: I have an image stack of 256 pixels x 256 pixels x 6000 frames that I would convert into a matrix of 65,536 pixels x 6000 frames before PCA. If I set 5,000 pixels outside the FOV to 0, would remove them and now have a matrix of 60,536 pixels x 6000 frames.
> 
> You need to keep track of the indices of those pixels so you can reconstruct images later.
> 
> Thanks, Sarah

Thank Sarah for explaining this!

**Comment by cgaletzka** [comment]
Hi Sarah,

Thank you very much for the quick reply. It‘s working nicely now.

Best,
Cedric

**Comment by cgaletzka** [comment]
Hi Sarah, 

Thank you for your quick reply. It is working nicely now!
